### ISSUE TITLE
error: package javax.jws does not exist

### ISSUE THREAD

**Issue by VFUC** [uniba-dsg/soa-ws-assignment-template#1]
Just wanted to let you know that I've encountered the following error when trying to build this cloned template"

`/.../soa-ws-assignment-template/src/main/java/de/uniba/dsg/jaxws/MusicApiImpl.java:9: error: package javax.jws does not exist`

I was able to resolve this by adding the following dependency to the build.gradle file:
`compile group: 'org.glassfish.main.javaee-api', name: 'javax.jws', version: '3.1.2.2'`

This could be missing for everyone, but it could also be that it only occurs on my system (macOS 10.14.4, IntelliJ IDEA CE, openjdk 12.0.1) or I configured something incorrectly.

Either way, if someone runs into the same issue, maybe this will help :) Cheers!

**Comment by stefan-kolb** [comment]
This is due to Java 12 which does not include `javax.jws` as far as I know.

**Comment by VFUC** [comment]
Good to know, thanks!

**Comment by stefan-kolb** [comment]
@johannes-manner Are you still working with Java 8 here?

**Comment by johannes-manner** [comment]
Yeah, we are still working with Java8 since all the pools and labs have only Java8 installed as far as I know. 
I will change the template as soon as a new version of Java is installed in our pools and labs.
